### ISSUE TITLE
can-scramble solutions wrong?

### ISSUE THREAD

**Issue by kaido42** [mre/the-coding-interview#60]
at least php-version of the solution fails with testing "aabb" and "aaac" ...

**Comment by mre** [comment]
You are right @kaido42. What a shame. 😞 
The problem is, that I simply sum up the [byte values](http://php.net/manual/en/function.ord.php) of the characters. 'a' is 97, 'b' is 98, and 'c' is 99.
Therefore 'a' + 'a' + 'b' + 'b' has the same sum as 'a' + 'a' + 'a+ 'c', which is 390.
What I should have done instead, is to check if the occurrences of each character match.

An `O(n)` way to do that would be to go over each character in the input one-by-one and increase a counter for the character in an associative array. I do something similar in the Python solution.
Another option would be to sort the inputs and compare the characters from left to right. That would be `O(n*log n)`, though.
Both options would be fine for me.

Could you make a pull request to fix that? Would be great. 😃

**Comment by kaido42** [comment]
>> Could you make a pull request to fix that? Would be great

sry, too lazy :)

**Comment by jklewa** [comment]
^^ Happy hacktober
